baseURL = "https://gabrieldougherty.com/"
languageCode = "en-us"
title = "Gabriel Dougherty"
theme = "kiss"
copyright = "&copy; Gabriel Dougherty 2021"
disqusShortname = "shortname"
googleAnalytics = ""
Paginate = 5 # Number of posts per page
enableRobotsTXT = true
disablePathToLower = true

[params.rss] # Adding this tag enables RSS feed
includeContent = true # Includes whole content in rss
authorName = "Gabriel Dougherty" # Author full name
authorEmail = "contact@gabrieldougherty.com" # Author email

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = false # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article
codeCopy = true # Add copy button above code blocks
taxonomiesCount = true # Add taxonomies count

[params.features]
disqusOnDemand = true  # Load Disqus comments on click


[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]
github = "GabrielDougherty"
email = "contact@gabrieldougherty.com"
linkedin = "gabriel-dougherty"
rss = "index.xml" # Add this to show RSS button in social.

[params.social.config]
platforms = ["github","email","linkedin"]

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true

[params.sections_right]
"/docs/Gabriel_Dougherty_Resume.pdf" = "Resume"
