baseURL = "https://gabrieldougherty.com/"
languageCode = "en-us"
title = "Gabriel Dougherty"
theme = "kiss"
copyright = "&copy; Gabriel Dougherty 2019-2025"
# disqusShortname = "shortname"  # Commented out to disable Disqus
googleAnalytics = "" # Add your GA4 measurement ID here (G-XXXXXXXXXX)
Paginate = 5 # Number of posts per page
enableRobotsTXT = true
enableGitInfo = false # Disable git info for faster builds
canonifyURLs = false
enableEmoji = false # Disable emoji processing for speed

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  [minify.tdewolff.html]
    keepWhitespace = false
  [minify.tdewolff.css]
    keepCSS2 = true
    precision = 0

[sitemap]
changefreq = "weekly"
priority = 0.5
filename = "sitemap.xml"

[params.rss] # Adding this tag enables RSS feed
includeContent = true # Includes whole content in rss
authorName = "Gabriel Dougherty" # Author full name
authorEmail = "contact@gabrieldougherty.com" # Author email

[params.assets]
customCSS = ["css/minimal.css"]
preload = ["css/critical.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "Gabriel Dougherty - Software Engineer" # Title for home page
description = "Gabriel Dougherty's blog - Software engineering, C++, CMake, and technical insights"
poweredby = false # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article
codeCopy = true # Add copy button above code blocks
taxonomiesCount = true # Add taxonomies count
dateFormat = "January 2, 2006" # Consistent date format

[params.features]
# disqusOnDemand = true  # Disabled along with Disqus


[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]
github = "GabrielDougherty"
email = "contact@gabrieldougherty.com"
linkedin = "gabriel-dougherty"
resume = "docs/gabriel_dougherty_resume.pdf"
rss = "index.xml" # Add this to show RSS button in social.

[params.social.config]
platforms = ["github","email","linkedin","resume"]

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
  [markup.highlight]
    style = "github"
    lineNos = false
    tabWidth = 2
